development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: rediss://red-cjd0eh45kgrc73fv3nng:5QtiAKc7oGuGOL5vAHBsOeEVHGuWNH4M@singapore-redis.render.com:6379
  channel_prefix: BookingDoctor_production
