stripe_publishable_key: "pk_test_51Ncgu3JD1fB4LR0qbOTp0PsHQTEg8Ut5aawu1SaxrRUcdT3HEN1FNc8175IF49X6nxymbktyk7bA2OsVB0gvOlqq00kowuH95h"
stripe_secret_key: "sk_test_51Ncgu3JD1fB4LR0qkJYMDQsa6onZ3syzFz1fsJ3KzCRO6DSjZb5WkqY7n3EunrudS0DV7hpqqp90SGZ0lF53icvt00kiIoLMjY"
